<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="task1" Id="{20a40416-a3f2-4129-a137-0b4baf41b1bb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM task1
VAr
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="task1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>