<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Watering" Id="{3c8812c0-276c-4c26-8d31-84af572d2303}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Watering
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Watering">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>